# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Sex' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    inhibit_all_warnings! 
 # use_frameworks!
    pod 'MKDropdownMenu'
    pod 'HTHorizontalSelectionList'
    pod 'AFNetworking'
    pod 'ReactiveCocoa', '~>2.5'
    pod 'MJRefresh'
    pod 'SDWebImage'
    pod 'Masonry'
    pod 'MJExtension'
    pod 'XXNibBridge'
  # Pods for Sex

end
