# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Sex' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    inhibit_all_warnings! 
 # use_frameworks!
    pod 'MKDropdownMenu', '~> 1.3'
    pod 'HTHorizontalSelectionList'
    pod 'IQKeyboardManager', '~> 3.3.5'
    pod 'AFNetworking', '~> 2.5'
    pod 'ReactiveCocoa', '~>2.5'
    pod 'MJRefresh'
    pod 'SDWebImage'
    pod 'Masonry'
    pod 'MJExtension'
    pod 'XXNibBridge'
    pod 'Aspects', '~> 1.4.1'
    pod 'SDCycleScrollView', '~> 1.65'
  # Pods for Sex

end
