# Uncomment this line to define a global platform for your projec
 platform :ios, '9.0'

target 'Sex' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage', '~> 3.8.2'
  pod 'MJExtension', '~> 3.0.13'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'ReactiveCocoa', '~>2.5'
  pod 'SVProgressHUD'
  pod 'Masonry', '~> 1.0.2'
  pod 'MKDropdownMenu', '~> 1.3'
  pod 'XXNibBridge', '~> 2.3.1'
  pod 'MKDropdownMenu', '~> 1.3'
  pod 'HTHorizontalSelectionList'
  pod 'SAMKeychain'
  # Pods for Sex

end
